version: '2'
services:
  jenkins:
    image: 'jenkins:lab'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - '8080:8080'
    restart: always
